### ISSUE TITLE
XML file format for evaluation.py

### ISSUE THREAD

**Issue by omair18** [opencv/training_toolbox_caffe#18]
@AlexanderDokuchaev what is the .xml annotation file format used for evaluating the model in  ```evaluation.py``` ?

**Comment by AlexanderDokuchaev** [comment]
@omair18  

It's look like this

```xml
<?xml version='1.0' encoding='utf-8'?>
<opencv_storage>
  <image000000>
    <path>1.jpg</path>
    <object000000>
      <type>pedestrian</type>
      <id>0</id>
      <bbox>295 14 61 175</bbox>
    </object000000>
    <object000001>
      <type>pedestrian</type>
      <id>1</id>
      <bbox>355 47 44 186</bbox>
    </object000001>
  </image000000>
</opencv_storage>
```
Format of box is  `<bbox>X Y W H</bbox>`

Dont ask why used several different formats, it was hard time :disappointed: 
And it will no be fixed because we dont use Caffe anymore.

**Comment by omair18** [comment]
Great. Thanks. :)
