### ISSUE TITLE
Training stuck in Solver:Step

### ISSUE THREAD

**Issue by burialpine** [opencv/training_toolbox_caffe#6]
Training stuck in Solver:Step
I have tried both 1st stage and 2nd stage training. But both stuck in Solver::Step-> net_->ForwardBackward();
See log 
[ar.log](https://github.com/opencv/training_toolbox_caffe/files/2781741/ar.log)

My Training Steps as below
•        Organized training data
  data
├── annotation
│   ├── annotation_file_1.xml
├── images
│   └── video_1
│       ├── frame_000001.jpg
│       ├── frame_000002.jpg
               …
│       └── frame_000100.jpg
└── train_tasks.txt
•        Train_tasks.txt as below
/home/dl/yan/ar_training_kit/annotation/annotation_file_1.xml 400,680 /home/dl/yan/ar_training_kit/images/video_1
       
•        Run “../../../build/tools/caffe train --gpu=0 --solver=solver.prototxt” under ar_training_kit/caffe/models/person_detection_action_recognition/stage2__action_regognition

**Comment by evgeny-izutov** [comment]
1. Update you develop branch.
2. If you have changed the number of actions make sure it's correct according instructions.
3. Make sure you run with correct `PYTHONPATH` which should include path to `caffe/python`.

**Comment by burialpine** [comment]
> 1. Update you develop branch.
Updated
> 2. If you have changed the number of actions make sure it's correct according instructions.
I didn't change anything. But my annotation file just contains 3 actions. Will this impact?
> 3. Make sure you run with correct `PYTHONPATH` which should include path to `caffe/python`.
Yes, i included. If PYTHONPATH is not set,  training will fail at beginning when trying to use custom layers.

I still got training stuck.

**Comment by evgeny-izutov** [comment]
It's incorrect setup to train on 3-class annotation while data-layer expects 5 classes.

**Comment by burialpine** [comment]
So how to provide 5-class annotation if my video only contains 3 actions?
[annotation_file_1.zip](https://github.com/opencv/training_toolbox_caffe/files/2786211/annotation_file_1.zip)

**Comment by evgeny-izutov** [comment]
As it's mentioned in [instructions](https://github.com/opencv/training_toolbox_caffe#model-training) you should change the `.prototxt` files only to correct number of actions (3 actions instead of 5 like in example).

**Comment by burialpine** [comment]
hi, evgeny
Thanks for the advice. It is indeed caused by actions provided in my annotation files didn't contain all actions defined in $CAFFE_ROOT/python/custom_layers/actions_data_layer.py and prototxt.

Can we exit the training loop if we found annotations not match? It can help to find the problem very easily.

I can provide a little more details on how to figure out the issue
Run "../../../build/tools/caffe train --gpu=0 --solver=solver.prototxt" to start the training.
Check the training log

> 1818 I0122 11:21:45.921553 17816 _caffe.cpp:105] Found 0 tasks:
> 1819 I0122 11:21:45.921576 17816 _caffe.cpp:105] DataLayer stats: loaded 0 frames with 0 objects.
> 1820 I0122 11:21:45.921633 17816 _caffe.cpp:105] No labels

This means task is not recognized. You should check train_tasks.txt carefully. 

If actions provided doesn't contain all actions defined, the log will show

> 1817 I0124 10:37:54.015730 13524 _caffe.cpp:105] Found 1 tasks:
> 1818 I0124 10:37:54.015740 13524 _caffe.cpp:105]    0: /home/dl/yan/ar_training_kit/data/annotation/annotation_file_1.xml
> 1819 I0124 10:37:54.015748 13524 _caffe.cpp:105] Loading task /home/dl/yan/ar_training_kit/data/annotation/annotation_file_1.xml...
> 1820 I0124 10:37:54.018440 13524 _caffe.cpp:105] DataLayer stats: loaded 100 frames with 200 objects.
> 1821 I0124 10:37:54.018499 13524 _caffe.cpp:105] Labels:
> 1822 I0124 10:37:54.018512 13524 _caffe.cpp:105]    0: 000096 (48.24%) - 000096 frames
> 1823 I0124 10:37:54.018517 13524 _caffe.cpp:105]    1: 000101 (50.75%) - 000100 frames
> 1824 I0124 10:37:54.018522 13524 _caffe.cpp:105]    2: 000001 (0.50%) - 000001 frames
> 1825 I0124 10:37:54.018525 13524 _caffe.cpp:105]    3: 000001 (0.50%) - 000001 frames
> 1826 I0124 10:37:54.018529 13524 _caffe.cpp:105]    4: 000000 (0.00%) - 000000 frames
> 1827 Process Process-1:
> 1828 Traceback (most recent call last):
> 1829   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> 1830     self.run()
> 1831   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
> 1832     self._target(*self._args, **self._kwargs)
> 1833   File "/home/dl/yan/ar_training_kit/caffe/python/caffe/custom_layers/actions_data_layer.py", line 816, in _ids_queue_filler
> 1834     subset_ids = np.random.choice(class_frame_ids, min_queue_size, replace=False)
> 1835   File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
> 1836 ValueError: a must be non-empty

Here you can see action 4 has no frame contain it.
> 1826 I0124 10:37:54.018529 13524 _caffe.cpp:105]    4: 000000 (0.00%) - 000000 frames

After you provide all actions in annotation file, the issue is gone.

**Comment by evgeny-izutov** [comment]
Fixed. Added check of non-empty list of frames for each valid action.
