### ISSUE TITLE
failed to init AR weight from FD weights

### ISSUE THREAD

**Issue by burialpine** [opencv/training_toolbox_caffe#7]
I failed to init AR weight from FD weights
'dl@ice-prc-dl-server1:~/yan/ar_training_kit/caffe$ python python/rename_layers.py -i models/person_detection_action_rcognition/stage2__action_regognition/init_weights.caffemodel –o models/person_detection_action_recognition/stage2__action_regognition/ar_init_weights.caffemodel
Traceback (most recent call last):
  File "python/rename_layers.py", line 16, in <module>
    from caffe import set_mode_cpu
  File "/home/dl/yan/ar_training_kit/caffe/python/caffe/__init__.py", line 40, in <module>
    import custom_layers
ImportError: No module named 'custom_layers'

**Comment by burialpine** [comment]
I have custom_layers under caffe/python/caffe/custom_layers/

**Comment by evgeny-izutov** [comment]
As it's pointed in instructions you should add path to `caffe/python` to `PYTHONPATH` variable. You can do that simultaneous with main command : `PYTHONPATH=$PYTHONPATH:your_path_to_python_caffe python rename_layers.py`

**Comment by burialpine** [comment]
> As it's pointed in instructions you should add path to `caffe/python` to `PYTHONPATH` variable. You can do that simultaneous with main command : `PYTHONPATH=$PYTHONPATH:your_path_to_python_caffe python rename_layers.py`

I have already added this env but the error still happens

dl@ice-prc-dl-server1:~/yan/ar_training_kit/caffe$ python python/rename_layers.py -i models/person_detection_action_rcognition/stage2__action_regognition/init_weights.caffemodel -o models/person_detection_action_recognition/stage2__action_regognition/ar_init_weights.caffemodel -p "cl/"
Traceback (most recent call last):
  File "python/rename_layers.py", line 16, in <module>
    from caffe import set_mode_cpu
  File "/home/dl/yan/ar_training_kit/caffe/python/caffe/__init__.py", line 40, in <module>
    import custom_layers
ImportError: No module named 'custom_layers'
dl@ice-prc-dl-server1:~/yan/ar_training_kit/caffe$ env|grep PYTHONPATH
PYTHONPATH=/home/dl/yan/ar_training_kit/caffe/python/

**Comment by evgeny-izutov** [comment]
Try to run with mentioned above command: `PYTHONPATH=$PYTHONPATH:your_path_to_python_caffe python rename_layers.py`.

**Comment by burialpine** [comment]
hi, It seems to be caused by python3. 
When i use python2.7, the issue is gone.
